# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/freebsd13"

  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: <<-SHELL
    pkg install -y gmake ccache git flex bison readline p5-IPC-Run llvm pkgconf python3 libxslt openldap25-client gettext tcl86 krb5 screen htop
  SHELL

  # things to run as vagrant user
  $setup_tree = <<-SHELL
    # pull down the source tree
    git clone https://github.com/postgres/postgres.git

    # set up lazy scripts so I don't have to remember the options
    cd postgres
    echo './configure --prefix=$HOME/install --enable-cassert --enable-debug --enable-tap-tests --enable-nls --with-gssapi --with-icu --with-tcl --with-perl --with-python --with-pam --with-ldap --with-libxml --with-libxslt --with-lz4 --with-openssl --with-llvm --with-libs=/usr/local/lib --with-includes=/usr/local/include CC="ccache cc" CXX="ccache c++" CLANG="ccache clang90" LLVM_CONFIG="llvm-config90"' > reconfigure.sh
    echo 'gmake -s clean && gmake -s -j4 && gmake -s install' > rebuild.sh
    chmod +x reconfigure.sh rebuild.sh

    # warm up ccache by building and installing (it's not a provisioning
    # failure if this step fails, though)
    ./reconfigure.sh && ./rebuild.sh && gmake -s check || true
  SHELL
  config.vm.provision "shell", inline: $setup_tree, privileged: false

  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 4
  end
end

