# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "openindiana/hipster"
  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.forward_agent = true

  # install the packages we need
  config.vm.provision "shell", inline: <<-SHELL
    pkg install gcc-10 gdb flex bison autoconf ccache git vim screen library/icu pkg-config openldap
    # Sun's old LDAP library at /usr/lib/libldap.so doesn't have
    # ldap_start_tls_s, but package openldap installs libldap_r.so and
    # libldap-2.4.so, leaving in place the older libldap.so that postgres
    # can't build against.  Sadly, our configure script doesn't provide a way
    # to tell it to use -lldap-2.4, so...  adjust the libldap.so symlink.
    # This is a bit grotty.  (Build farm animal wrasse avoids the problem by
    # having a hand-compiled libldap that is in the library search patch
    # before the system library path, but I'm trying to use the packages
    # here...)
    rm -f /usr/lib/libldap.so
    ln -s libldap-2.4.so /usr/lib/libldap.so
    rm -f /usr/lib/amd64/libldap.so
    ln -s libldap-2.4.so /usr/lib/amd64/libldap.so
  SHELL

  # things to run as vagrant user
  $setup_tree = <<-SHELL
    # install local perl stuff we need for --enable-tap-tests to work
    # (this stuff is apparently not available via system-wide pkg install)
    # XXX how can we use less version-specific paths here?
    # XXX it seems ugly to be exposing libperl.so with LD_LIBRARY_PATH,
    # perhaps there is a package that would put it somewhere more cromulent
    # (Again, build farm animal wrasse has its own hand-built perl...)
    echo 'export PATH=$PATH:/usr/perl5/5.24/bin' >> ~/.profile
    echo 'export PERL5LIB=~/perl5/lib/perl5' >> ~/.profile
    echo 'export LD_LIBRARY_PATH=/usr/perl5/5.24/lib/i86pc-solaris-thread-multi-64/CORE' >> ~/.profile
    . ~/.profile
    cpan -T IPC::Run

    # pull down the source tree
    git clone https://github.com/postgres/postgres.git

    # set up lazy scripts so I don't have to remember the options
    cd postgres
    # Notes:
    #   --with-llvm gets some way if you install "clang90" above, but fails
    #     with: ld: fatal: file /usr/clang/9.0/lib/libLLVM-9.so: wrong ELF
    #           class: ELFCLASS64
    echo './configure --prefix=$HOME/install --enable-cassert --enable-debug --enable-tap-tests --enable-nls --with-gssapi --with-icu --with-tcl --with-perl --with-python --with-pam --with-ldap --with-libxml --with-libxslt --with-lz4 --with-openssl --with-includes="/usr/include/openldap" CC="ccache gcc"' > reconfigure.sh
    echo 'gmake -s clean && gmake -s -j4 && gmake -s install' > rebuild.sh
    chmod +x reconfigure.sh rebuild.sh

    # warm up ccache by building and installing (it's not a provisioning
    # failure if this step fails, though)
    ./reconfigure.sh && ./rebuild.sh && gmake -s check || true
  SHELL
  config.vm.provision "shell", inline: $setup_tree, privileged: false

  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 4
  end
end

