# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"

  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: <<-SHELL
    pkg_add gmake git bison autoconf-2.69p3 readline
  SHELL

  # get a source tree and some scripts to start things off
  $setup_tree = <<-SHELL
    git clone https://github.com/postgres/postgres.git
    cd postgres
    echo './configure --prefix=$HOME/install --enable-cassert --enable-debug CC="ccache cc"' > reconfigure.sh
    echo 'gmake -s clean && gmake -s -j4 && gmake -s install && gmake -s check' > rebuild.sh
    chmod +x reconfigure.sh rebuild.sh
  SHELL
  config.vm.provision "shell", inline: $setup_tree, privileged: false

  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 4
  end
end

