# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"

  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: <<-SHELL
    pkg_add -z ccache gmake git bison autoconf-2.69 readline screen-- p5-IPC-Run icu4c python3 libxml libxslt openldap-client--gssapi tcl-8.6.8 gettext-tools llvm
  SHELL

  # things to run as vagrant user
  $setup_tree = <<-SHELL
    # pull down the source tree
    git clone https://github.com/postgres/postgres.git

    # set up lazy scripts so I don't have to remember the options
    #
    # Notes:
    #   --with-bsd-auth replaces --with-pam on OpenBSD
    #   --with-gssapi not used yet (which package is needed for this?!)
    #   --with-llvm requires llvm package even though there are parts of
    #     LLVM in the base system; not enough parts
    cd postgres
    echo './configure --prefix=$HOME/install --enable-cassert --enable-debug --enable-tap-tests --enable-nls --with-icu --with-tcl --with-perl --with-python --with-bsd-auth --with-ldap --with-libxml --with-libxslt --with-lz4 --with-openssl --with-llvm CC="ccache cc" CXX="ccache c++" CLANG="ccache /usr/local/bin/clang" LLVM_CONFIG="/usr/local/bin/llvm-config"' > reconfigure.sh
    echo 'gmake -s clean && gmake -s -j4 && gmake -s install' > rebuild.sh
    chmod +x reconfigure.sh rebuild.sh

    # warm up ccache by building and installing (it's not a provisioning
    # failure if this step fails, though)
    ./reconfigure.sh && ./rebuild.sh && gmake -s check || true
  SHELL
  config.vm.provision "shell", inline: $setup_tree, privileged: false

  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 4
  end
end

